(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



r0= ToExpression[($CommandLine)[[-1]]];

Print["r0 = ", r0];


(*SetDirectory[NotebookDirectory[]<>"h1_ab data/hlmi/"];*)
SetDirectory["~/Code/SecondOrder/FirstOrderData/data/ret_data/"];


r0ToString[r_Integer]:=ToString[r]
r0ToString[r_]:=ToString[N[r]]


Clear[drh]


M=1;
pm=+1;
file="hlmi_r"<>r0ToString[r0]<>"_high_acc.dat";
data=Sort[Import[file],#1[[3]]<#2[[3]]||(#1[[3]]==#2[[3]]&&#1[[1]]<#2[[1]])||(#1[[3]]==#2[[3]]&&#1[[1]]==#2[[1]]&&#1[[2]]<#2[[2]])&];
Scan[(h[Round[#[[3]]]][Round[#[[1]]],Round[#[[2]]]]=#[[4]]+I #[[5]])&,data]
If[pm==-1,
Scan[(drh[Round[#[[3]]]][Round[#[[1]]],Round[#[[2]]]]=#[[6]]+I #[[7]])&,data],
Scan[(drh[Round[#[[3]]]][Round[#[[1]]],Round[#[[2]]]]=#[[8]]+I #[[9]])&,data]
];
lmax=Round[data[[-1,1]]];


(*h[9][1,0]=0*)


h[9][1,0](*This should be non-zero*)


\[CapitalOmega]=Sqrt[M/r0^3];
f0=1-2/r0;
E0=f0/Sqrt[1-3M/r0];
L0=Sqrt[M r0]/( Sqrt[1-3M/r0]);
t0=0;
\[Phi]0=0;
ut=Sqrt[r0/(r0-3M)];
u\[Phi]=\[CapitalOmega] ut;


If[pm==-1,
Block[{A,f0=1-2M/r0,f=1-2M/r,P=(r^2+2M r+4M^2),Q=r^3-M r^2-2M^2 r+12M^3,\[ScriptCapitalE]=Sqrt[r0/(r0-3M)](1-2M/r0)},
A=(2\[ScriptCapitalE])/(3M r0 f0) (M-(r0-3M)Log[f0]);
httl0=-((A f M)/r^3)P;
hrrl0=A/(r^3 f) Q;
h\[Phi]\[Phi]l0=A f P;
h1l0=2Sqrt[\[Pi]]r(httl0+f^2 hrrl0);
h6l0=2Sqrt[\[Pi]] r/f (httl0-f^2 hrrl0);
h3l0=4Sqrt[\[Pi]] 1/r h\[Phi]\[Phi]l0;
huul0=httl0 (Sqrt[r0/(r0-3M)])^2+h\[Phi]\[Phi]l0 (1/r0 Sqrt[M/(r0-3M)])^2;
huurl0=D[huul0,r];
],
Block[{A,f0=1-2M/r0,f=1-2M/r,P=(r^2+2M r+4M^2),Q=r^3-M r^2-2M^2 r+12M^3,\[ScriptCapitalE]=Sqrt[r0/(r0-3M)](1-2M/r0)},
A=(2\[ScriptCapitalE])/(3M r0 f0) (M-(r0-3M)Log[f0]);
httl0=(2\[ScriptCapitalE])/(3r^4 r0 f0) (3r^3 (r0-r)+M^2 (r0^2-12M r0+8M^2)+(r0-3M)(-r M(r+4M)+r P f Log[f]+8M^3 Log[r0/r]));
hrrl0=-((2\[ScriptCapitalE])/(3r^4 r0 f0 f^2))(-r^3r0-2M r(r0^2-6M r0-10M^2)+3M^2 (r0^2-12M r0+8M^2)+(r0-3M)(5M r^2+r/M Q f Log[f]-8M^2 (2r-3M)Log[r0/r]));
h\[Phi]\[Phi]l0=-((2\[ScriptCapitalE])/(9r r0 f0))(3r0^2 M-80M^2 r0+156M^3+(r0-3M)(-3 r^2-12M r+3r/M P f Log[f]+44M^2+24M^2 Log[r0/r]));
h1l0=2Sqrt[\[Pi]]r(httl0+f^2 hrrl0);
h6l0=2Sqrt[\[Pi]] r/f (httl0-f^2 hrrl0);
h3l0=4Sqrt[\[Pi]] 1/r h\[Phi]\[Phi]l0;
huul0=httl0 (Sqrt[r0/(r0-3M)])^2+h\[Phi]\[Phi]l0 (1/r0 Sqrt[M/(r0-3M)])^2;
huurl0=D[huul0,r];
]];


h1l0/.r->r0//N


h[1][0,0]=h1l0/.r->r0;
h[2][0,0]=0;
h[3][0,0]=h3l0/.r->r0;
h[6][0,0]=h6l0/.r->r0;


drh[1][0,0]=D[h1l0,r]/.r->r0;
drh[3][0,0]=D[h3l0,r]/.r->r0;
drh[6][0,0]=D[h6l0,r]/.r->r0;


f0=1-(2M)/r0;
E0=f0 (1-(3M)/r0)^(-1/2);


f=1-(2M)/r;


P=r^2+2r M+4M^2;
Q=r^3-r^2 M-2r M^2+12M^3;
W=3r^3-r^2 M-4r M^2-28 M^3/3;
K=r^3 M-5r^2 M^2-20r M^3/3+28 M^4;


H[1]={-f,f^-1,1};
H[2]={-((f M)/r^3)P,f^-1/r^3 Q,f/r^2 P};
H[3]={-(M^4/r^4),(M^3 f^-2 (3M-2r))/r^4,M^3/r^3};
H[4]={
M/r^4 (W+r P f Log[f]-8M^3 Log[r/M]),
f^-2/r^4 (K-r Q f Log[f]-8M^3 (2r-3M)Log[r/M]),
1/r^3 (3r^3-W-r P f Log[f]+8M^3 Log[r/M])
};


Table[Simplify[R[1][i]=2Sqrt[\[Pi]] r/M (H[i][[1]]+f^2 H[i][[2]])],{i,1,4}];
Table[Simplify[R[3][i]=4Sqrt[\[Pi]]r/M H[i][[3]]],{i,1,4}];
Table[Simplify[R[6][i]=2Sqrt[\[Pi]]r/(f M)(H[i][[1]]-f^2 H[i][[2]])],{i,1,4}];


\[CapitalPhi]={
{-R[1][1],-R[1][2],R[1][3],R[1][4]},
{-R[3][1],-R[3][2],R[3][3],R[3][4]},
D[{-R[1][1],-R[1][2],R[1][3],R[1][4]},r],
D[{-R[3][1],-R[3][2],R[3][3],R[3][4]},r]
};


J1=-16 \[Pi] E0/r0 SphericalHarmonicY[0,0,\[Pi]/2,0];
source={0,0,J1,J1/f};


coeffs=Simplify[Inverse[\[CapitalPhi]] . source]/.r->r0;


h1MonoIn[r0_,r_]=FullSimplify[coeffs[[1]]R[1][1]+coeffs[[2]]R[1][2],Assumptions->{r>2,r0>3}];
h1MonoOut[r0_,r_]=FullSimplify[coeffs[[3]]R[1][3]+coeffs[[4]]R[1][4],Assumptions->{r>2,r0>3}];

h3MonoIn[r0_,r_]=FullSimplify[coeffs[[1]]R[3][1]+coeffs[[2]]R[3][2],Assumptions->{r>2,r0>3}];
h3MonoOut[r0_,r_]=FullSimplify[coeffs[[3]]R[3][3]+coeffs[[4]]R[3][4],Assumptions->{r>2,r0>3}];

h6MonoIn[r0_,r_]=FullSimplify[coeffs[[1]]R[6][1]+coeffs[[2]]R[6][2],Assumptions->{r>2,r0>3}];
h6MonoOut[r0_,r_]=FullSimplify[coeffs[[3]]R[6][3]+coeffs[[4]]R[6][4],Assumptions->{r>2,r0>3}];


3/2 coeffs[[4]]-1/2 coeffs[[1]]-E0
(coeffs[[1]]+coeffs[[2]])R[1][2]-h1l0/.r->r0//Simplify
-coeffs[[1]](R[1][1]-R[1][2])+coeffs[[3]]R[1][3]+coeffs[[4]]R[1][4]-h1l0/.r->r0//Simplify


drh[1][0,0]//N
D[-coeffs[[1]](R[1][1]-R[1][2])+coeffs[[3]]R[1][3]+coeffs[[4]]R[1][4],r]/.r->r0//N


h[1][0,0]=h1MonoOut[r0,r0];
h[2][0,0]=0;
h[3][0,0]=h3MonoOut[r0,r0];
h[6][0,0]=h6MonoOut[r0,r0];


drh[1][0,0]=D[h1MonoOut[r0,r],r]/.r->r0;
drh[2][0,0]=0;
drh[3][0,0]=D[h3MonoOut[r0,r],r]/.r->r0;
drh[6][0,0]=D[h6MonoOut[r0,r],r]/.r->r0;


\[CapitalDelta]Ures={
{4,-1.218697151452634517941334353974874134928609746080172069406`23.590386429739784},
{5,-0.466652374199557836412225161485162309229366023170960152473`24.889522639101646},
{6,-0.296027509290014557246406361963108949196835722669411428456`25.419145845117352},
{7,-0.220847527432247320112330936003665566586038561057528482604`25.635905250725287},
{8,-0.177719743553592433415669398255075986725487233010340091921`25.755789733374556},
{9,-0.149360608917907227443367685936306228547169421315686960648`25.829283533444993},
{10,-0.129122274392049459254420256458358416205241409069147726258`25.872190367064196},
{12,-0.101935572386267131876206804400126407909383489698600743335`25.929573047891683},
{14,-0.08438195340957112261633532098376433925936777409186955891`25.965621752208325},
{16,-0.072055057429345011234164502097763956686708880301263094466`25.98386637477755},
{18,-0.062901899428239009003894696519926379081429666751292234828`26.01295668178191},
{20,-0.055827718602493851311267093148080022485612805638625520548`26.036230220994284},
{30,-0.03577831357182050986732568997436596498034140777077027247`26.09180233365747},
{40,-0.026339677413704841864372776163448898199019055341415775218`26.095348045970663},
{50,-0.020844656530595422496571425238359077965482926279574138469`26.123634542848208},
{60,-0.017247593292679154815048138212868674496005621022258221132`26.13929441533291},
{70,-0.014709646361721720354214641837500983408706072059791161867`26.145408772984833},
{80,-0.012822960575771495927632988541913687864526304437186292008`26.149770409327516},
{90,-0.011365315607411427036230106958530790821605470263701469278`26.153023499985057},
{100,-0.010205282730027605459422033603532224735780593359358240344`26.125836937406635},
{500,-0.00200804044413976405236634839329892728424350039010843653`26.164277519343592},
{1000,-0.001002005027714142967612419850153694970270578501317571659`26.15238218304416},
{5000,-0.000200080040044302370180208554839512932968281504797392199`26.091450956289606}
};


\[CapitalOmega]\[Phi]=Sqrt[M/r0^3];


f=1-2M/r;
Y[l_,m_,\[Theta]_,\[Phi]_]:=SphericalHarmonicY[l,m,\[Theta],\[Phi]];
YV1[l_,m_,\[Theta]1_,\[Phi]_]:=If[l>=1,1/(l(l+1)) D[Y[l,m,\[Theta],\[Phi]],\[Theta]]/.\[Theta]->\[Theta]1,0]
YV2[l_,m_,\[Theta]_,\[Phi]_]:=If[l>=1,(I m)/(l(l+1)) Y[l,m,\[Theta],\[Phi]]/Sin[\[Theta]],0]
YT1[l_,m_,\[Theta]1_,\[Phi]_]:=If[l>=2,(l-2)!/(l+2)! (Sin[\[Theta]]D[D[Y[l,m,\[Theta],\[Phi]],\[Theta]]/Sin[\[Theta]],\[Theta]]+(m^2 Y[l,m,\[Theta],\[Phi]])/Sin[\[Theta]]^2)/.\[Theta]->\[Theta]1,0]
YT2[l_,m_,\[Theta]1_,\[Phi]_]:=If[l>=2,2 (l-2)!/(l+2)! D[I m Y[l,m,\[Theta],\[Phi]]/Sin[\[Theta]],\[Theta]]/.\[Theta]->\[Theta]1,0]


h[1,1][l_,m_]:=1/(2r) (h[1][r]+f h[6][r])Y[l,m,\[Theta],\[Phi]]Exp[-I m \[CapitalOmega]\[Phi] t]
h[1,2][l_,m_]:=1/(2r f) h[2][r] Y[l,m,\[Theta],\[Phi]]Exp[-I m \[CapitalOmega]\[Phi] t]
h[1,3][l_,m_]:=1/2 (h[4][r] YV1[l,m,\[Theta],\[Phi]]+h[8][r] YV2[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[1,4][l_,m_]:=1/2 Sin[\[Theta]](h[4][r]YV2[l,m,\[Theta],\[Phi]]-h[8][r]YV1[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[2,2][l_,m_]:=1/(2r f^2) (h[1][r]-f h[6][r])Y[l,m,\[Theta],\[Phi]]Exp[-I m \[CapitalOmega]\[Phi] t]
h[2,3][l_,m_]:=1/(2f) (h[5][r] YV1[l,m,\[Theta],\[Phi]]+h[9][r] YV2[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[2,4][l_,m_]:=1/(2f) Sin[\[Theta]](h[5][r] YV2[l,m,\[Theta],\[Phi]]-h[9][r] YV1[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[3,3][l_,m_]:=r/2 (h[3][r] Y[l,m,\[Theta],\[Phi]]+h[7][r]YT1[l,m,\[Theta],\[Phi]]+h[10][r] YT2[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[3,4][l_,m_]:=r/2 Sin[\[Theta]](h[7][r] YT2[l,m,\[Theta],\[Phi]]-h[10][r]YT1[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]
h[4,4][l_,m_]:=r/2 Sin[\[Theta]]^2 (h[3][r]Y[l,m,\[Theta],\[Phi]]-h[7][r]YT1[l,m,\[Theta],\[Phi]]-h[10][r]YT2[l,m,\[Theta],\[Phi]])Exp[-I m \[CapitalOmega]\[Phi] t]


AtParticle:={r->r0,\[Theta]->\[Pi]/2,\[Phi]->0,t->0};
InLorenzGauge[l_,m_]:={h[a_,b_]:>h[a,b][l,m],\!\(\*SuperscriptBox[\(h\), 
TagBox[
RowBox[{"(", 
RowBox[{"a_", ",", "b_", ",", "c_", ",", "d_"}], ")"}],
Derivative],
MultilineFunction->None]\)[e_,f_]:>D[h[e,f][l,m],{t,a},{r,b},{\[Theta],c},{\[Phi],d}],h[a_][_]:>h[a][l,m],h[a_]'[_]:>drh[a][l,m]}


h[a_,b_][l_]:=h[a,b][l]=Sum[If[m==0,1,2]Re[h[a,b][l,m]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]


dth[a_,b_][l_]:=dth[a,b][l]=Sum[If[m==0,1,2]Re[D[ h[a,b][l,m],t]/.InLorenzGauge[l,m]]/.AtParticle,{m,0,l}]
drh[a_,b_][l_]:=drh[a,b][l]=Sum[If[m==0,1,2]Re[D[ h[a,b][l,m],r]/.InLorenzGauge[l,m]]/.AtParticle,{m,0,l}]
d\[Theta]h[a_,b_][l_]:=d\[Theta]h[a,b][l]=Sum[If[m==0,1,2]Re[D[ h[a,b][l,m],\[Theta]]/.InLorenzGauge[l,m]]/.AtParticle,{m,0,l}]
d\[Phi]h[a_,b_][l_]:=d\[Phi]h[a,b][l]=Sum[If[m==0,1,2]Re[D[ h[a,b][l,m],\[Phi]]/.InLorenzGauge[l,m]]/.AtParticle,{m,0,l}]


Table[{l,Abs[Sum[If[m==0,1,2] 1/(2f) Sin[\[Theta]]Re[(*h[5][r] YV2[l,m,\[Theta],\[Phi]]*)-h[9][r] YV1[l,m,\[Theta],\[Phi]]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]]},{l,0,15}];


ut^2 h[1,1][2,2]+ 2ut u\[Phi] h[1,4][2,2]+u\[Phi]^2 h[4,4][2,2]/.InLorenzGauge[2,2]/.AtParticle


ut^2 h[1,1][2,1]+ 2ut u\[Phi] h[1,4][2,1]+u\[Phi]^2 h[4,4][2,1]/.InLorenzGauge[2,1]/.AtParticle


Table[{l,Abs[Sum[If[m==0,1,2]Re[1/(2f) Sin[\[Theta]]h[9][r] YV1[l,m,\[Theta],\[Phi]]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]]},{l,0,15}]//ListLogLogPlot


Table[{l,Abs[Sum[If[m==0,1,2]Re[h[9][r]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]]},{l,0,50}]


Table[{l,Abs[Sum[If[m==0,1,2]Re[h[2,4][l,m]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]]},{l,0,50}]//ListLogLogPlot


monopoleReplace={
h[1][r]->h1l0-h1MonoOut[r0,r],
h[3][r]->h3l0-h3MonoOut[r0,r],
h[6][r]->h6l0-h6MonoOut[r0,r],
h[1]'[r]->D[h1l0-h1MonoOut[r0,r],r],
h[3]'[r]->D[h3l0-h3MonoOut[r0,r],r],
h[6]'[r]->D[h6l0-h6MonoOut[r0,r],r]
};


\[Delta]huu=Simplify[h[1,1][0,0]ut^2+2h[1,4][0,0]ut u\[Phi]+h[4,4][0,0]u\[Phi]^2/.monopoleReplace/.{r->r0,\[Theta]->\[Pi]/2}];
\[Delta]drhuu=Simplify[D[h[1,1][0,0]ut^2+2h[1,4][0,0]ut u\[Phi]+h[4,4][0,0]u\[Phi]^2,r]/.monopoleReplace/.{r->r0,\[Theta]->\[Pi]/2}];


K=EllipticK[M/(r0-2M)];
\[CapitalLambda]1=(l(l+1))/((2l-1)(2l+3));
\[CapitalLambda]2=((l-1)l(l+1)(l+2))/((2l-3)(2l-1)(2l+3)(2l+5));
hP[1,1]=(4(r0-M)K)/(\[Pi] r0^2) Sqrt[(r0-2M)/(r0-3M)];
hP[1,2]=0;
hP[1,3]=0;
hP[1,4]=-((32 M^(1/2) K)/(\[Pi] r0^(1/2)))Sqrt[(r0-2M)/(r0-3M)]\[CapitalLambda]1;
hP[2,2]=(4K)/\[Pi] (r0-3M)^(1/2)/(r0-2M)^(3/2);
hP[2,3]=0;
hP[2,4]=0;
hP[3,3]=(4r0 K)/\[Pi] Sqrt[(r0-2M)/(r0-3M)]-(64M r0 K)/(\[Pi] (r0-2M)^(1/2) (r0-3M)^(1/2)) \[CapitalLambda]2;
hP[3,4]=0;
hP[4,4]=(4r0 K)/\[Pi] Sqrt[(r0-2M)/(r0-3M)]+(64M r0 K)/(\[Pi] (r0-2M)^(1/2) (r0-3M)^(1/2)) \[CapitalLambda]2;


hR[a_,b_][l_]:=h[a,b][l]-hP[a,b]


Clear[hRlData]
hRlData[a_,b_]:=hRlData[a,b]=Table[{l,hR[a,b][l]},{l,0,lmax}];


Table[hRlData[a,b],{a,{1,4}},{b,{1,4}}];


\[ScriptCapitalE]=EllipticE[M/(r0-2M)];


drhP[-1][1,1]=-((r0-M)/(r0^(5/2) (r0-3M)^(1/2)));
drhP[0][1,1]=(2(r0-M)((r0-2M)\[ScriptCapitalE]-2(r0-4M)K))/(\[Pi] r0^3 (r0-3M)^(1/2) (r0-2M)^(1/2));
drhP[-1][1,2]=0;
drhP[0][1,2]=0;
drhP[-1][1,3]=0;
drhP[0][1,3]=0;
drhP[-1][1,4]=If[l>=1,(2 (M^(1/2))  )/(r0 (r0-3M)^(1/2)),0];
drhP[0][1,4]=-((16M ^(1/2) ((r0-2 M) EllipticE[-(M/(2 M-r0))]+2 M EllipticK[-(M/(2 M-r0))]))/(\[Pi] r0^(3/2) (r0-3M)^(1/2) (r0-2M)^(1/2)))\[CapitalLambda]1;

drhP[-1][2,2]=-(r0-3 M)^(1/2)/(r0^(1/2) (r0-2 M)^2);
drhP[0][2,2]=(2 (r0-3M)^(1/2) ((r0-2 M)\[ScriptCapitalE]-2 r0 K))/(\[Pi] r0 (r0-2 M)^(5/2));
drhP[-1][2,3]=0;
drhP[0][2,3]=0;
drhP[-1][2,4]=0;
drhP[0][2,4]=0;

drhP[-1][3,3]=-Sqrt[r0/(r0-3M)]+If[l>=2,(M r0^(1/2))/((r0-2M)(r0-3M)^(1/2)),0];
drhP[0][3,3]=2 ( \[ScriptCapitalE]+2K)/\[Pi] Sqrt[(r0-2M)/(r0-3M)]-(32 M (\[ScriptCapitalE]+2K))/(\[Pi] (r0-3M)^(1/2) (r0-2M)^(1/2)) \[CapitalLambda]2;
drhP[-1][3,4]=0;
drhP[0][3,4]=0;

drhP[-1][4,4]=- Sqrt[(r0/(-3 M+r0))]+If[l>=2, M /(Sqrt[1-(3 M)/r0] (2 M-r0)),0];
drhP[0][4,4]=(2  (EllipticE[-(M/(2 M-r0))]+2 K))/\[Pi] Sqrt[(r0-2 M)/(r0-3 M)]+\[CapitalLambda]2 (32M(\[ScriptCapitalE]+2 K))/( \[Pi] (r0-3M)^(1/2) (r0-2M)^(1/2));



drhR[a_,b_][l_]:=drh[a,b][l]-drhP[-1][a,b](2l+1)-drhP[0][a,b]


Clear[drhRlData]
drhRlData[a_,b_]:=drhRlData[a,b]=Table[{l,drhR[a,b][l]},{l,0,lmax}];


Show[
ListLogLogPlot[Abs[drhRlData[1,1]]]
]


d\[Phi]hP[-1][a_,b_]:=0;
d\[Phi]hP[0][1,1]=0;
d\[Phi]hP[0][1,2]=-((32((r0-2M)\[ScriptCapitalE]-(r0-3M)K))/(\[Pi] M^(1/2) r0^(3/2)))Sqrt[(r0-2M)/(r0-3M)]\[CapitalLambda]1;
d\[Phi]hP[0][1,3]=0;
d\[Phi]hP[0][1,4]=0;
d\[Phi]hP[0][2,2]=0;
d\[Phi]hP[0][2,3]=0;
d\[Phi]hP[0][2,4]=(16((r0-2M) \[ScriptCapitalE] -(r0-3M)K))/(\[Pi] (r0-2M)^(1/2) (r0-3M)^(1/2)) (\[CapitalLambda]1+4\[CapitalLambda]2);
d\[Phi]hP[0][3,3]=0;
d\[Phi]hP[0][3,4]=0;
d\[Phi]hP[0][4,4]=0;


d\[Phi]hR[a_,b_][l_]:=d\[Phi]h[a,b][l]-d\[Phi]hP[-1][a,b](2l+1)-d\[Phi]hP[0][a,b]


Clear[d\[Phi]hRlData]
d\[Phi]hRlData[a_,b_]:=d\[Phi]hRlData[a,b]=Table[{l,d\[Phi]hR[a,b][l]},{l,0,lmax}];


dthP[-1][a_,b_]:=0;
dthP[0][a_,b_]:=-\[CapitalOmega]\[Phi] d\[Phi]hP[0][a,b];


dthR[a_,b_][l_]:=dth[a,b][l]-dthP[-1][a,b](2l+1)-dthP[0][a,b]


Clear[dthRlData]
dthRlData[a_,b_]:=dthRlData[a,b]=Table[{l,dthR[a,b][l]},{l,0,lmax}];


d\[Theta]hP[-1][a_,b_]:=0;
d\[Theta]hP[0][a_,b_]:=0;


d\[Theta]hR[a_,b_][l_]:=d\[Theta]h[a,b][l]-d\[Theta]hP[-1][a,b](2l+1)-d\[Theta]hP[0][a,b]


Clear[d\[Theta]hRlData]
d\[Theta]hRlData[a_,b_]:=d\[Theta]hRlData[a,b]=Table[{l,d\[Theta]hR[a,b][l]},{l,0,lmax}];


hRlData[2,4]//Abs//ListLogLogPlot


hRlData[2,4]//Total


DetPoly[n_]:=Product[(2l-2k+1)(2l+2k+1),{k,1,n}]^-1;
AccelReg[data_,Nmax_,nmax_]:=FindFit[data[[-nmax;;]],Sum[RP[j]DetPoly[j],{j,1,Nmax}],Flatten[{Table[RP[j],{j,1,Nmax}]}],l];


hRlData2[a_,b_]:=hRlData2[a,b]=Block[{accel,dtaccel,draccel,d\[Theta]accel,d\[Phi]accel,Nmax=10,nmax=25},
accel=AccelReg[hRlData[a,b],Nmax,nmax];
dtaccel=AccelReg[dthRlData[a,b],Nmax,nmax];
draccel=AccelReg[drhRlData[a,b],Nmax,nmax];
d\[Theta]accel=AccelReg[d\[Theta]hRlData[a,b],Nmax,nmax];
d\[Phi]accel=AccelReg[d\[Phi]hRlData[a,b],Nmax,nmax];
Table[{
l,
hRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.accel,{j,1,Nmax-1}],
dthRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.dtaccel,{j,1,Nmax-1}],
drhRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.draccel,{j,1,Nmax-1}],
d\[Theta]hRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.d\[Theta]accel,{j,1,Nmax-1}],
d\[Phi]hRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.d\[Phi]accel,{j,1,Nmax-1}]
},{l,0,Length[hRlData[a,b]]-1}]
]


huu=Total[hRlData2[1,1][[All,2]]]ut^2+2 Total[hRlData2[1,4][[All,2]]] ut u\[Phi]+Total[hRlData2[4,4][[All,2]]]u\[Phi]^2


(*hRlData2[1,1][[All,2]]//Total
hRlData[1,1][[All,2]]//Total

hRlData2[1,1][[All,4]]//Total
drhRlData[1,1][[All,2]]//Total*)


\[Alpha]=1/Sqrt[r0(r0-3)];
\[CapitalDelta]U=(1-3/r0)^(-1/2) ((r0-2)/(r0-3) \[Alpha]+1/2 (huu+\[Delta]huu))


1-\[CapitalDelta]U/\[CapitalDelta]Ures[[Flatten[Position[\[CapitalDelta]Ures[[All,1]],r0]]]][[1,2]]


Interpolation[Import["~/BHPToolkit/CircularOrbitSelfForceData/Schwarzschild/Redshift_and_spin_invariants.dat"][[7;;,{1,2}]],InterpolationOrder->5][r0]


(*For radiative components, which don't require regularization, use hRlData. Otherwise hRlData2*)
h1ab={
{1,1,Total[hRlData2[1,1][[;;,2]]],Total[dthRlData[1,1][[;;,2]]],Total[hRlData2[1,1][[;;,4]]]  ,Total[d\[Theta]hRlData[1,1][[;;,2]]],Total[d\[Phi]hRlData[1,1][[;;,2]]]},
{1,2,Total[hRlData[1,2][[;;,2]]]  ,Total[hRlData2[1,2][[;;,3]]]  ,Total[drhRlData[1,2][[;;,2]]],Total[d\[Theta]hRlData[1,2][[;;,2]]],Total[hRlData2[1,2][[;;,6]]] },
{1,3,Total[hRlData[1,3][[;;,2]]]  ,Total[dthRlData[1,3][[;;,2]]]  ,Total[drhRlData[1,3][[;;,2]]],Total[d\[Theta]hRlData[1,3][[;;,2]]],Total[d\[Phi]hRlData[1,3][[;;,2]]] },
{1,4,Total[hRlData2[1,4][[;;,2]]],Total[dthRlData[1,4][[;;,2]]],Total[hRlData2[1,4][[;;,4]]]  ,Total[d\[Theta]hRlData[1,4][[;;,2]]],Total[d\[Phi]hRlData[1,4][[;;,2]]]},
{2,2,Total[hRlData2[2,2][[;;,2]]],Total[dthRlData[2,2][[;;,2]]],Total[hRlData2[2,2][[;;,4]]]  ,Total[d\[Theta]hRlData[2,2][[;;,2]]],Total[d\[Phi]hRlData[2,2][[;;,2]]]},
{2,3,Total[hRlData2[2,3][[;;,2]]],Total[dthRlData[2,3][[;;,2]]],Total[drhRlData[2,3][[;;,2]]],Total[hRlData2[2,3][[;;,5]]],Total[d\[Phi]hRlData[2,3][[;;,2]]]},
{2,4,Total[hRlData[2,4][[;;,2]]]  ,Total[hRlData2[2,4][[;;,3]]]  ,Total[drhRlData[2,4][[;;,2]]],Total[d\[Theta]hRlData[2,4][[;;,2]]],Total[hRlData2[2,4][[;;,6]]]},
{3,3,Total[hRlData2[3,3][[;;,2]]],Total[dthRlData[3,3][[;;,2]]],Total[hRlData2[3,3][[;;,4]]]  ,Total[d\[Theta]hRlData[3,3][[;;,2]]],Total[d\[Phi]hRlData[3,3][[;;,2]]]},
{3,4,Total[hRlData2[3,4][[;;,2]]],Total[dthRlData[3,4][[;;,2]]],Total[drhRlData[3,4][[;;,2]]]  ,Total[d\[Theta]hRlData[3,4][[;;,2]]],Total[d\[Phi]hRlData[3,4][[;;,2]]]},
{4,4,Total[hRlData2[4,4][[;;,2]]],Total[dthRlData[4,4][[;;,2]]],Total[hRlData2[4,4][[;;,4]]]  ,Total[d\[Theta]hRlData[4,4][[;;,2]]],Total[d\[Phi]hRlData[4,4][[;;,2]]]}
}


(*SetDirectory["/Users/niels/Dropbox/Mathematica/2nd_order/h1_ab data/"];*)
SetDirectory["~/Code/SecondOrder/FirstOrderData/data/R_data/"];
data=Import["h1Rab.dat"];
pos=Position[data[[All,1]],N[r0]];
If[Length[pos]==0,
AppendTo[data,Flatten[{N[r0],h1ab[[All,3]],h1ab[[All,4]],h1ab[[All,5]],h1ab[[All,6]],h1ab[[All,7]]}]];,
If[Length[pos]==1,
data[[pos[[1]]]]=Flatten[{N[r0],h1ab[[All,3]],h1ab[[All,4]],h1ab[[All,5]],h1ab[[All,6]],h1ab[[All,7]]}];,
Print["Two data entries for r0=" <>ToString[r0]]
]
]
Export["h1Rab.dat",Sort[data]];


dhRlData2[a_,b_]:=Block[{accel,Nmax=10,nmax=25},
accel=AccelReg[drhRlData[a,b],Nmax,nmax];
Table[{l,drhRlData[a,b][[l+1,2]]-Sum[RP[j]DetPoly[j]/.accel,{j,1,Nmax-1}]},{l,0,Length[drhRlData[a,b]]-1}]
]


drhuu=Total[dhRlData2[1,1][[All,2]]]ut^2+2 Total[dhRlData2[1,4][[All,2]]] ut u\[Phi]+Total[dhRlData2[4,4][[All,2]]]u\[Phi]^2


{FrReg,FrIrreg}={1/2 (1-(2M)/r0)drhuu,1/2 (1-(2M)/r0)(drhuu+\[Delta]drhuu)}


Akcay={{6,2.4466495 10^-2},{8,1.8357830 10^-2},{10,1.3389470 10^-2}};
Berndtson={{6,4.9685669 10^-2},{8,2.7112763 10^-2},{10,1.7454613 10^-2}};


SetDirectory["~/Code/SecondOrder/FirstOrderData/data/R_data/"];
data=Import["Fr.dat"];
pos=Position[data[[All,1]],r0];
If[Length[pos]==0,
AppendTo[data,{N[r0],FrReg,FrIrreg}],
If[Length[pos]==1,
data[[pos[[1]]]]={N[r0],FrReg,FrIrreg},
Print["Two data entries for r0=" <>ToString[r0]]
]
]
Export["Fr.dat",Sort[data]]


Table[{l,Abs[Sum[If[m==0,1,2]Re[h[2,4][l,m]]/.InLorenzGauge[l,m]/.AtParticle,{m,0,l}]]},{l,0,50}]//ListLogLogPlot


ListLogLogPlot[hRlData[1,4]//Re//Abs]
