# GSF_circ_output: code to compute the first-order in the mass ratio Lorenz-gauge metric perturbation from a particle in a circular orbit about a Schwarzschild black hole
# Copyright (C) 2017  Niels Warburton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys, os
env = Environment()


# pretty output
if ARGUMENTS.get('VERBOSE') != '1':
  if sys.stdout.isatty():
    env['CCCOMSTR'] = "\033[92mCompiling\033[0m $TARGET"
    env['LINKCOMSTR'] = "\033[94mLinking\033[0m $TARGET"
  else:
    env['CCCOMSTR'] = "Compiling $TARGET"
    env['LINKCOMSTR'] = "Linking $TARGET"
    
# Build options
env['ENV']['TERM'] = os.environ['TERM']

env['LIBPATH']  = ['/usr/lib/x86_64-linux-gnu/hdf5/serial/']
env['LIBS']     = ['gsl' , 'gslcblas', 'hdf5', 'hdf5_hl', 'm']
env['CC']       = 'mpicc'
env['CPPPATH']  = ['../include', '/usr/include/hdf5/serial']
env['CCFLAGS']  = ['-Wall', '-Wno-unused-variable', '-g', '-O2', '-DGSL_COMPLEX_LEGACY']

sources = ['GSF_ecc.c', 'Runge-Kutta.c', 'SF_data.c', 'array_handling.c', 'boundary_conditions.c', 'convergence_tests.c', 'error_estimate.c', 'file_output.c', 'gauge_fields.c', 'gauge_fields_on_grid.c', 'grid.c', 'h1R_on_grid.c', 'libSch.c', 'math_funcs.c', 'ode_systems.c', 'scaling_coefficients.c', 'sources.c', 'static_monopole.c']

env.Program('../h1Lorenz', sources)
